@startuml persons-service-der

hide circle

entity Persons {
    id **PK** : SERIAL
    ---
    name : TEXT
    ---
    birthDate : DATE
    ---
    email : TEXT
    ---
    cityId **FK** : INTEGER
}

entity Cities {
    id **PK** : SERIAL
    ---
    name : TEXT
    ---
    provinceId **FK** : INTEGER
}

entity Provinces {
    id **PK** : SERIAL
    ---
    name : TEXT
    ---
    countryId **FK** : INTEGER
}

entity Countries {
    id **PK** : SERIAL
    ---
    name : TEXT
}

Persons::cityId }|-right--||Cities::id
Cities::provinceId }|-down--||Provinces::id
Provinces::countryId }|-left--||Countries::id

@enduml